###
POST http://localhost:8888/registration/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "jerry",
  "lastname": "jess",
  "email": "test@yahoo.fr",
  "password": "12345"
}

### "email": "{{$randomEmail}}"